### ISSUE TITLE
training run default params

### ISSUE THREAD

**Issue by hyu2000** [michaelnny/alpha_zero#5]
Hi Michael, great work! 

I have some question on the params you use for 9x9 Go run. Do you mind sharing what you overrode during the actual run?

BTW, I think this default is probably too big:
flags.DEFINE_integer(
    'games_per_ckpt',
    5000,
    'Collect minimum number of self-play games using the last checkpoint before creating the next checkpoint.',
)

I believe AZ updates its param constantly, which probably means as soon as they fill up a mini-batch, they would perform an update. I'd guess a new checkpoint would be produced probably every few hundreds of games.

What's your thinking?

Thanks

**Comment by michaelnny** [comment]
Hi, the parameters we use to train the agent are documented in the corresponding scripts. We didn't fine-tune these hyper-parameters, so you may try different combinations on your own.

**Comment by hyu2000** [comment]
I see. BTW, I browsed some of the matches vs CrazyStone, and saw one game result is actually wrong. A white chain is obviously dead, but Tromp-Taylor scoring would count it...

**Comment by michaelnny** [comment]
This has already been documented in the limitations section in the readme profile.
